BOT_INIT_BASE_IMPORTS = """\nimport disnake\nfrom disnake.ext import commands\nimport _____project_name_for_imports_____.config as cfg\nfrom _____project_name_for_imports_____.utils.parser import parse_config\nfrom _____project_name_for_imports_____.utils.messages import send_error_message\n\nfrom cogs.events_handlers import EventsCog\nfrom cogs.help import HelpCog\nfrom _____project_name_for_imports_____.cogs.all_messages import AllMessagesCog\n\n """
BOT_INIT_COMMAND_COG_IMPORT = """\nfrom cogs.moderation import ModerationCog\n """
BOT_INIT_ANOTHER_COG_IMPORT = """\nfrom cogs.another import AnotherCog\n\n """
BOT_INIT_BODY = """\nintents = disnake.Intents.all()\ncommand_sync_flags = commands.CommandSyncFlags.default()\ncommand_sync_flags.sync_commands_debug = cfg.SYNC_COMMANDS_DEBUG\n\nbot = commands.Bot(command_prefix=cfg.PREFIX,\n                   intents=intents,\n                   command_sync_flags=command_sync_flags)\n\nbot.add_cog(HelpCog(bot))\nbot.add_cog(EventsCog(bot))\nbot.add_cog(AllMessagesCog(bot))\n\n """
BOT_INIT_ADD_COMMAND_COG = """\nbot.add_cog(ModerationCog(bot))\n """
BOT_INIT_ADD_ANOTHER_COG = """\nbot.add_cog(AnotherCog(bot))\n"""
